### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by edsu** [RDFLib/rdflib-sqlalchemy#11]
From Travis It looks like the unit tests are failing under python3?

```
ERROR: Failure: SyntaxError (invalid syntax (term.py, line 1559))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 190, in load_module
    return load_package(name, filename)
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/imp.py", line 160, in load_package
    return _bootstrap.SourceFileLoader(name, path).load_module(name)
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/build/src/test/__init__.py", line 1, in <module>
    from rdflib import plugin
  File "/home/travis/virtualenv/python3.3.5/src/rdflib/rdflib/__init__.py", line 112, in <module>
    from rdflib.term import (
nose.proxy.SyntaxError: invalid syntax (term.py, line 1559)
```

**Comment by gjhiggins** [comment]
Fixed in commit: ccec3517b69c4abda40e72a22f4cb65b5b33ba11
