### ISSUE TITLE
Build error for Python 2.7 for MySQL

### ISSUE THREAD

**Issue by mwatts15** [RDFLib/rdflib-sqlalchemy#76]
Error observed during test `testAdd (test.test_sqlalchemy_mysql.SQLAMySQLContextTestCase)`.

https://travis-ci.org/github/RDFLib/rdflib-sqlalchemy/jobs/764264566

```
Traceback (most recent call last):

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/test/test_sqlalchemy_mysql.py", line 64, in setUp

    uri=self.uri, storename=self.storename)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/test/context_case.py", line 29, in setUp

    self.graph.open(uri, create=True)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/rdflib/graph.py", line 373, in open

    return self.__store.open(configuration, create)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/rdflib_sqlalchemy/store.py", line 276, in open

    self.engine = sqlalchemy.create_engine(url, **kwargs)

  File "<string>", line 2, in create_engine

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned

    return fn(*args, **kwargs)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine

    u = _url.make_url(url)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 711, in make_url

    return _parse_rfc1738_args(name_or_url)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 774, in _parse_rfc1738_args

    return URL.create(name, **components)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 152, in create

    cls._str_dict(query),

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 211, in _str_dict

    for key, value in dict_items

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 211, in <dictcomp>

    for key, value in dict_items

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 189, in _assert_value

    return tuple(_assert_value(elem) for elem in val)

  File "/home/travis/build/RDFLib/rdflib-sqlalchemy/.tox/py27/lib/python2.7/site-packages/sqlalchemy/engine/url.py", line 189, in <genexpr>

    return tuple(_assert_value(elem) for elem in val)
```
The last frame repeats until max recursion depth is reached.

**Comment by mwatts15** [comment]
Python 2.7 is no longer supported, so closing this.
